site_name: HTCF
theme: 
  name: material
  logo: htcf_rev_sm.png
  favicon: images/favicon.png
  features:
    - navigation.instant
    - toc.integrate
  palette:
    scheme: wustl_red
    
extra_css:
  - stylesheets/extra.css

extra:
  font:
    text: 'Roboto'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list
  - def_list
  - meta
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - macros
  - search
  
extra:
  lts:
    price: 7.77

nav:
- About: 'index.md'
- 'using/getstarted.md'
#- Doing Work:
#    - 'using.md'
    #- Running Jobs: runningjobs.md
    #- The Queue: using/queue.md
    #- Using the HTCF: 'using/index.md'
    #- Batch Jobs: 'using/batch.md'
    #- Interactive Jobs: 'using/interactive.md'
    #- Job Accounting: 'using/accounting.md'
    #  #- queue.md
    #  #- runningjobs.md
- 'policies.md'
- 'storage/index.md'
- 'storage/compare.md'
#- Storage: 
    #- Overview: 'storage/index.md'
    #- HTS: 'storage/hts.md'
    #- REF: 'storage/ref.md'
    #- LTS: 'storage/lts.md'
    #- LTOS: 'storage/ltos.md'
    #- Beta: 'storage/new_index.md'
- Software:
  - Getting Started: 'software.md'
  - 'software/r/index.md'
  - 'software/rstudio/index.md'
  - 'software/jupyter/index.md'
  - Examples:
    - 'software/examples/r_mpi/index.md'
# - R+MPI: 'software/examples/r_with_mpi.md'
